[build]
  bin = "tmp/piccolo"
  cmd = "go build -o tmp/piccolo ./cmd/piccolo"
  watch_dir = ["."]
  include_ext = ["go", "html"]
  exclude_dir = ["pg_data"]

[log]
  log_level = "warn"

[watch]
  include_ext = ["go", "html"]
