[build]
  bin = "tmp/piccolo"
  cmd = "go build -o tmp/piccolo cmd/piccolo/main.go"
  watch_dir = ["."]
  include_ext = ["go", "html"]

[log]
  log_level = "warn"

[watch]
  include_ext = ["go", "html"]
